# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86539215e0c56b71d2532ab60a97055255c7f6caef00137afe5bb28b830da9777b4727bf830a8f58f667be22a9391318faf8cc0eb2dbaa8331e8dfda35e4aa83

test:
  secret_key_base: 4ee691877f44cb6ca8295214a336d14d800f55c54bdd9d1b52217d66098ba863f7802d40e8541a6962e53cc55e27426acabf4c3f04f1f27fc5173d5ddd17b264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
